Plugins: fetch variant features from VEP cache or Ensembl API
Ensembl/ensembl-variation pull request #1099
Opened 2024-06-20 17:22 UTC by nuno-agostinho

https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6290: new subroutines to allow plugins to fetch variant features using:
- (indexed or non-indexed) VEP cache if `--cache` is enabled.
- Otherwise, Ensembl API if `--database` is enabled.

You can test the changes here using PR https://github.com/Ensembl/VEP_plugins/pull/723.

Please test fetching variants from indexed cache, non-indexed cache and database.

2024-07-09 15:29 UTC, nakib103 commented on modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm
> +  if (defined($as = $self->_get_AnnotationSource('VariationTabix'))) {
Hi @nuno-agostinho , should this `_get_AnnotationSource` should also be part of `BaseVepPlugin.pm`. It seems to generic to be in Paralogues plugin only

2024-07-09 15:49 UTC, nakib103 requested changes

2024-07-09 15:49 UTC, nakib103 commented on modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm
> +    $self->{slow_warning} = 1;
```suggestion
    warn("Using non-indexed VEP cache is slow; for optimal performance, please use indexed VEP cache\n")
      unless $self->{skip_slow_warning};
    $self->{skip_slow_warning} = 1;
```

2024-07-10 08:51 UTC, nakib103 requested changes

2024-07-10 08:51 UTC, nakib103 commented on modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm
> +      my $gz = gzopen($file, 'rb');
Need to use `use Compress::Zlib;` for `gzopen` function to work.

2024-07-10 08:51 UTC, nakib103 commented on modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm
> +        next unless overlap($start, $end, $var->{start}, $var->{end});
@nuno-agostinho, `overlap` function is not defined here or imported, hence not working.

2024-07-10 08:56 UTC, nakib103 requested changes

2024-07-10 08:56 UTC, nakib103 commented on modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm
> +        my $var = $as->parse_variation($line);
the non-indexed cache lines do not contain the chromosome, we should add it manually.

```suggestion
        my $var = $as->parse_variation($line);
        $var->{chr} = $c;
```

2024-08-23 09:59 UTC, closed without merging

2024-08-23 09:59 UTC, nuno-agostinho commented
The current design of ensembl-vep and ensembl-variation make @nakib103's suggestions not trivial to implement.

As such, I will close this PR. All changes in this PR were now included in https://github.com/Ensembl/VEP_plugins/pull/723.

The changes proposed here will be reconsidered for the next version of VEP.