Update ClinVar script to import somatic classifications
Ensembl/ensembl-variation pull request #1117
Opened 2024-08-19 10:47 UTC by dglemos

Ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5941

2025-01-13 09:34 UTC, nakib103 requested changes

2025-01-15 14:54 UTC, dglemos commented on modules/Bio/EnsEMBL/Variation/Utils/Config.pm
> +    'Tier III - Uncertain significance',
Good spot!
It is not mentioned in the docs but it is associated to some records - we should add it to the list.

2025-01-31 09:35 UTC, nakib103 approved these changes
LGTM!~ Thanks @dglemos for the updates.

2025-02-04 09:26 UTC, jamie-m-a approved these changes
The logic seems sound, we have reviewed this in meetings as well and Sarah has had oversight of the changes. Ok to merge.

2025-02-04 09:40 UTC, merged