Fix coord system and add non-human test data
Ensembl/ensembl-variation pull request #667
Opened 2020-12-01 17:13 UTC by dglemos

HGVS genomic didn't work for some non-human species because they only have `primary_assembly` coord system.
Linked to https://github.com/Ensembl/ensembl-variation/pull/592 
Example for cow:
1:g.346786A>C

2020-12-07 08:23 UTC, helensch requested changes
The code update works on release databases.

Modifications are need for the test to use the new test database.
The new test databases (variation and core) should include a table.sql to be set up.

I suggest also testing that the new test database can be patched for future releases

2020-12-08 10:35 UTC, dglemos commented on modules/t/variationFeatureAdaptor.t
> +my $lrg_hgvsg = 'LRG_293:g.69535N>G';
As the branching is happening now, we'll leave the tests as they are now. 
The reference allele will be updated later as described in ENSVAR-3862.

2020-12-08 10:36 UTC, dglemos commented
@helensch thank you for the review. As discussed, the test db will be updated later as described here ENSVAR-3862.

2020-12-08 10:55 UTC, helensch approved these changes

2020-12-08 12:06 UTC, merged

2020-12-08 12:10 UTC, helensch commented
Merged into master and release/103